// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: inspector/v1/inspector.proto

package v1connect

import (
	v1 "ax-distiller/proto/inspector/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InspectorName is the fully-qualified name of the Inspector service.
	InspectorName = "Inspector"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InspectorGetStructProcedure is the fully-qualified name of the Inspector's GetStruct RPC.
	InspectorGetStructProcedure = "/Inspector/GetStruct"
	// InspectorShowProcedure is the fully-qualified name of the Inspector's Show RPC.
	InspectorShowProcedure = "/Inspector/Show"
	// InspectorExpandProcedure is the fully-qualified name of the Inspector's Expand RPC.
	InspectorExpandProcedure = "/Inspector/Expand"
)

// InspectorClient is a client for the Inspector service.
type InspectorClient interface {
	GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error)
	Show(context.Context, *connect.Request[v1.ShowRequest]) (*connect.Response[v1.ShowResponse], error)
	Expand(context.Context, *connect.Request[v1.ExpandRequest]) (*connect.Response[v1.ExpandResponse], error)
}

// NewInspectorClient constructs a client for the Inspector service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInspectorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InspectorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inspectorMethods := v1.File_inspector_v1_inspector_proto.Services().ByName("Inspector").Methods()
	return &inspectorClient{
		getStruct: connect.NewClient[v1.GetStructRequest, v1.GetStructResponse](
			httpClient,
			baseURL+InspectorGetStructProcedure,
			connect.WithSchema(inspectorMethods.ByName("GetStruct")),
			connect.WithClientOptions(opts...),
		),
		show: connect.NewClient[v1.ShowRequest, v1.ShowResponse](
			httpClient,
			baseURL+InspectorShowProcedure,
			connect.WithSchema(inspectorMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		expand: connect.NewClient[v1.ExpandRequest, v1.ExpandResponse](
			httpClient,
			baseURL+InspectorExpandProcedure,
			connect.WithSchema(inspectorMethods.ByName("Expand")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inspectorClient implements InspectorClient.
type inspectorClient struct {
	getStruct *connect.Client[v1.GetStructRequest, v1.GetStructResponse]
	show      *connect.Client[v1.ShowRequest, v1.ShowResponse]
	expand    *connect.Client[v1.ExpandRequest, v1.ExpandResponse]
}

// GetStruct calls Inspector.GetStruct.
func (c *inspectorClient) GetStruct(ctx context.Context, req *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error) {
	return c.getStruct.CallUnary(ctx, req)
}

// Show calls Inspector.Show.
func (c *inspectorClient) Show(ctx context.Context, req *connect.Request[v1.ShowRequest]) (*connect.Response[v1.ShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// Expand calls Inspector.Expand.
func (c *inspectorClient) Expand(ctx context.Context, req *connect.Request[v1.ExpandRequest]) (*connect.Response[v1.ExpandResponse], error) {
	return c.expand.CallUnary(ctx, req)
}

// InspectorHandler is an implementation of the Inspector service.
type InspectorHandler interface {
	GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error)
	Show(context.Context, *connect.Request[v1.ShowRequest]) (*connect.Response[v1.ShowResponse], error)
	Expand(context.Context, *connect.Request[v1.ExpandRequest]) (*connect.Response[v1.ExpandResponse], error)
}

// NewInspectorHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInspectorHandler(svc InspectorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inspectorMethods := v1.File_inspector_v1_inspector_proto.Services().ByName("Inspector").Methods()
	inspectorGetStructHandler := connect.NewUnaryHandler(
		InspectorGetStructProcedure,
		svc.GetStruct,
		connect.WithSchema(inspectorMethods.ByName("GetStruct")),
		connect.WithHandlerOptions(opts...),
	)
	inspectorShowHandler := connect.NewUnaryHandler(
		InspectorShowProcedure,
		svc.Show,
		connect.WithSchema(inspectorMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	inspectorExpandHandler := connect.NewUnaryHandler(
		InspectorExpandProcedure,
		svc.Expand,
		connect.WithSchema(inspectorMethods.ByName("Expand")),
		connect.WithHandlerOptions(opts...),
	)
	return "/Inspector/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InspectorGetStructProcedure:
			inspectorGetStructHandler.ServeHTTP(w, r)
		case InspectorShowProcedure:
			inspectorShowHandler.ServeHTTP(w, r)
		case InspectorExpandProcedure:
			inspectorExpandHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInspectorHandler returns CodeUnimplemented from all methods.
type UnimplementedInspectorHandler struct{}

func (UnimplementedInspectorHandler) GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("Inspector.GetStruct is not implemented"))
}

func (UnimplementedInspectorHandler) Show(context.Context, *connect.Request[v1.ShowRequest]) (*connect.Response[v1.ShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("Inspector.Show is not implemented"))
}

func (UnimplementedInspectorHandler) Expand(context.Context, *connect.Request[v1.ExpandRequest]) (*connect.Response[v1.ExpandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("Inspector.Expand is not implemented"))
}
