// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: inspector/v1/inspector.proto

package v1connect

import (
	v1 "ax-distiller/proto/inspector/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FooServeName is the fully-qualified name of the FooServe service.
	FooServeName = "FooServe"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FooServeTransformProcedure is the fully-qualified name of the FooServe's Transform RPC.
	FooServeTransformProcedure = "/FooServe/Transform"
)

// FooServeClient is a client for the FooServe service.
type FooServeClient interface {
	Transform(context.Context, *connect.Request[v1.Foo]) (*connect.Response[v1.Foo], error)
}

// NewFooServeClient constructs a client for the FooServe service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFooServeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FooServeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fooServeMethods := v1.File_inspector_v1_inspector_proto.Services().ByName("FooServe").Methods()
	return &fooServeClient{
		transform: connect.NewClient[v1.Foo, v1.Foo](
			httpClient,
			baseURL+FooServeTransformProcedure,
			connect.WithSchema(fooServeMethods.ByName("Transform")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fooServeClient implements FooServeClient.
type fooServeClient struct {
	transform *connect.Client[v1.Foo, v1.Foo]
}

// Transform calls FooServe.Transform.
func (c *fooServeClient) Transform(ctx context.Context, req *connect.Request[v1.Foo]) (*connect.Response[v1.Foo], error) {
	return c.transform.CallUnary(ctx, req)
}

// FooServeHandler is an implementation of the FooServe service.
type FooServeHandler interface {
	Transform(context.Context, *connect.Request[v1.Foo]) (*connect.Response[v1.Foo], error)
}

// NewFooServeHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFooServeHandler(svc FooServeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fooServeMethods := v1.File_inspector_v1_inspector_proto.Services().ByName("FooServe").Methods()
	fooServeTransformHandler := connect.NewUnaryHandler(
		FooServeTransformProcedure,
		svc.Transform,
		connect.WithSchema(fooServeMethods.ByName("Transform")),
		connect.WithHandlerOptions(opts...),
	)
	return "/FooServe/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FooServeTransformProcedure:
			fooServeTransformHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFooServeHandler returns CodeUnimplemented from all methods.
type UnimplementedFooServeHandler struct{}

func (UnimplementedFooServeHandler) Transform(context.Context, *connect.Request[v1.Foo]) (*connect.Response[v1.Foo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("FooServe.Transform is not implemented"))
}
