// @generated by protoc-gen-es v2.11.0
// @generated from file inspector/v1/inspector.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file inspector/v1/inspector.proto.
 */
export declare const file_inspector_v1_inspector: GenFile;

/**
 * @generated from message Foo
 */
export declare type Foo = Message<"Foo"> & {
  /**
   * @generated from field: int64 bar = 1;
   */
  bar: bigint;
};

/**
 * Describes the message Foo.
 * Use `create(FooSchema)` to create a new message.
 */
export declare const FooSchema: GenMessage<Foo>;

/**
 * @generated from service FooServe
 */
export declare const FooServe: GenService<{
  /**
   * @generated from rpc FooServe.Transform
   */
  transform: {
    methodKind: "unary";
    input: typeof FooSchema;
    output: typeof FooSchema;
  },
}>;

