// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inspector/v1/inspector.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bar           int64                  `protobuf:"varint,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_inspector_v1_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_v1_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_inspector_v1_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetBar() int64 {
	if x != nil {
		return x.Bar
	}
	return 0
}

var File_inspector_v1_inspector_proto protoreflect.FileDescriptor

const file_inspector_v1_inspector_proto_rawDesc = "" +
	"\n" +
	"\x1cinspector/v1/inspector.proto\"\x17\n" +
	"\x03Foo\x12\x10\n" +
	"\x03bar\x18\x01 \x01(\x03R\x03bar2#\n" +
	"\bFooServe\x12\x17\n" +
	"\tTransform\x12\x04.Foo\x1a\x04.FooB3B\x0eInspectorProtoP\x01Z\x1fax-distiller/proto/inspector/v1b\x06proto3"

var (
	file_inspector_v1_inspector_proto_rawDescOnce sync.Once
	file_inspector_v1_inspector_proto_rawDescData []byte
)

func file_inspector_v1_inspector_proto_rawDescGZIP() []byte {
	file_inspector_v1_inspector_proto_rawDescOnce.Do(func() {
		file_inspector_v1_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspector_v1_inspector_proto_rawDesc), len(file_inspector_v1_inspector_proto_rawDesc)))
	})
	return file_inspector_v1_inspector_proto_rawDescData
}

var file_inspector_v1_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inspector_v1_inspector_proto_goTypes = []any{
	(*Foo)(nil), // 0: Foo
}
var file_inspector_v1_inspector_proto_depIdxs = []int32{
	0, // 0: FooServe.Transform:input_type -> Foo
	0, // 1: FooServe.Transform:output_type -> Foo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inspector_v1_inspector_proto_init() }
func file_inspector_v1_inspector_proto_init() {
	if File_inspector_v1_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspector_v1_inspector_proto_rawDesc), len(file_inspector_v1_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inspector_v1_inspector_proto_goTypes,
		DependencyIndexes: file_inspector_v1_inspector_proto_depIdxs,
		MessageInfos:      file_inspector_v1_inspector_proto_msgTypes,
	}.Build()
	File_inspector_v1_inspector_proto = out.File
	file_inspector_v1_inspector_proto_goTypes = nil
	file_inspector_v1_inspector_proto_depIdxs = nil
}
