// @generated by protoc-gen-es v2.11.0
// @generated from file inspector/v1/inspector.proto (syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file inspector/v1/inspector.proto.
 */
export const file_inspector_v1_inspector = /*@__PURE__*/
  fileDesc("ChxpbnNwZWN0b3IvdjEvaW5zcGVjdG9yLnByb3RvIhIKA0ZvbxILCgNiYXIYASABKAMyIwoIRm9vU2VydmUSFwoJVHJhbnNmb3JtEgQuRm9vGgQuRm9vQjNCDkluc3BlY3RvclByb3RvUAFaH2F4LWRpc3RpbGxlci9wcm90by9pbnNwZWN0b3IvdjFiBnByb3RvMw");

/**
 * Describes the message Foo.
 * Use `create(FooSchema)` to create a new message.
 */
export const FooSchema = /*@__PURE__*/
  messageDesc(file_inspector_v1_inspector, 0);

/**
 * @generated from service FooServe
 */
export const FooServe = /*@__PURE__*/
  serviceDesc(file_inspector_v1_inspector, 0);

