// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package stdb

import (
	"database/sql"
)

type StructureInstance struct {
	ID     int64
	AxID   sql.NullString
	Role   sql.NullString
	Shash  []byte
	Phash  []byte
	Parent sql.NullInt64
}
