// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package stdb

import (
	"context"
	"database/sql"
)

const createStructureInstance = `-- name: CreateStructureInstance :one


insert into structure_instance (ax_id, role, shash, phash, parent)
values (?, ?, ?, ?, ?)
returning id
`

type CreateStructureInstanceParams struct {
	AxID   sql.NullString
	Role   sql.NullString
	Shash  []byte
	Phash  []byte
	Parent sql.NullInt64
}

// TODO: remove later
// -- name: PruneOrphanedInstances :exec
// --
// -- This removes structure instances that are not the root
// delete from structure_instance
// where id != 1 and parent is null;
// TODO: remove later
// -- name: GetAncestors :many
// with recursive ancestor_cte(id, parent) as (
//
//	select id, parent from structure_instance
//	where id = ? limit 1
//
//	union all
//
//	-- 1. this query takes in the previous rows produced as the value of
//	--    `latest_ancestor`
//	-- 2. since the anchor query will produce only 1 row
//	-- 3. and for a single row as input for `latest_ancestor`, only 1 or 0
//	--    parents can be produced
//	-- 4. this recursive expression will return a list of ancestors from the
//	--    given anchor
//	select s.id, s.parent from structure_instance s
//	inner join latest_ancestor a
//		on s.id = a.parent
//
// )
// select id from ancestor_cte;
func (q *Queries) CreateStructureInstance(ctx context.Context, arg CreateStructureInstanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createStructureInstance,
		arg.AxID,
		arg.Role,
		arg.Shash,
		arg.Phash,
		arg.Parent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteInstance = `-- name: DeleteInstance :exec

delete from structure_instance
where id = ?
`

// TODO: remove later
// -- name: DeleteInstancesByParent :exec
// delete from structure_instance
// where parent = ?;
func (q *Queries) DeleteInstance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const getRoot = `-- name: GetRoot :one
select id, ax_id, role, shash, phash, parent from structure_instance
where parent is null
`

func (q *Queries) GetRoot(ctx context.Context) (StructureInstance, error) {
	row := q.db.QueryRowContext(ctx, getRoot)
	var i StructureInstance
	err := row.Scan(
		&i.ID,
		&i.AxID,
		&i.Role,
		&i.Shash,
		&i.Phash,
		&i.Parent,
	)
	return i, err
}

const getStruct = `-- name: GetStruct :one
select id, ax_id, role, shash, phash, parent from structure_instance
where id = ?
`

func (q *Queries) GetStruct(ctx context.Context, id int64) (StructureInstance, error) {
	row := q.db.QueryRowContext(ctx, getStruct, id)
	var i StructureInstance
	err := row.Scan(
		&i.ID,
		&i.AxID,
		&i.Role,
		&i.Shash,
		&i.Phash,
		&i.Parent,
	)
	return i, err
}

const getStructByAXID = `-- name: GetStructByAXID :one
select id, ax_id, role, shash, phash, parent from structure_instance
where ax_id = ?
`

func (q *Queries) GetStructByAXID(ctx context.Context, axID sql.NullString) (StructureInstance, error) {
	row := q.db.QueryRowContext(ctx, getStructByAXID, axID)
	var i StructureInstance
	err := row.Scan(
		&i.ID,
		&i.AxID,
		&i.Role,
		&i.Shash,
		&i.Phash,
		&i.Parent,
	)
	return i, err
}

const listChildren = `-- name: ListChildren :many
select id, ax_id, role, shash, phash, parent from structure_instance
where parent = ?
`

func (q *Queries) ListChildren(ctx context.Context, parent sql.NullInt64) ([]StructureInstance, error) {
	rows, err := q.db.QueryContext(ctx, listChildren, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructureInstance
	for rows.Next() {
		var i StructureInstance
		if err := rows.Scan(
			&i.ID,
			&i.AxID,
			&i.Role,
			&i.Shash,
			&i.Phash,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructInstByPHash = `-- name: ListStructInstByPHash :many
select id, ax_id, role, shash, phash, parent from structure_instance
where phash = ?
`

func (q *Queries) ListStructInstByPHash(ctx context.Context, phash []byte) ([]StructureInstance, error) {
	rows, err := q.db.QueryContext(ctx, listStructInstByPHash, phash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructureInstance
	for rows.Next() {
		var i StructureInstance
		if err := rows.Scan(
			&i.ID,
			&i.AxID,
			&i.Role,
			&i.Shash,
			&i.Phash,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructInstBySHash = `-- name: ListStructInstBySHash :many
select id, ax_id, role, shash, phash, parent from structure_instance
where shash = ?
`

func (q *Queries) ListStructInstBySHash(ctx context.Context, shash []byte) ([]StructureInstance, error) {
	rows, err := q.db.QueryContext(ctx, listStructInstBySHash, shash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructureInstance
	for rows.Next() {
		var i StructureInstance
		if err := rows.Scan(
			&i.ID,
			&i.AxID,
			&i.Role,
			&i.Shash,
			&i.Phash,
			&i.Parent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructPHash = `-- name: ListStructPHash :many
select phash from structure_instance
group by phash
`

func (q *Queries) ListStructPHash(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listStructPHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var phash []byte
		if err := rows.Scan(&phash); err != nil {
			return nil, err
		}
		items = append(items, phash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructSHash = `-- name: ListStructSHash :many
select shash from structure_instance
group by shash
`

func (q *Queries) ListStructSHash(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listStructSHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var shash []byte
		if err := rows.Scan(&shash); err != nil {
			return nil, err
		}
		items = append(items, shash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStruct = `-- name: UpdateStruct :exec
update structure_instance
set ax_id = ?,
	role = ?,
	shash = ?,
	phash = ?,
	parent = ?
where id = ?
`

type UpdateStructParams struct {
	AxID   sql.NullString
	Role   sql.NullString
	Shash  []byte
	Phash  []byte
	Parent sql.NullInt64
	ID     int64
}

func (q *Queries) UpdateStruct(ctx context.Context, arg UpdateStructParams) error {
	_, err := q.db.ExecContext(ctx, updateStruct,
		arg.AxID,
		arg.Role,
		arg.Shash,
		arg.Phash,
		arg.Parent,
		arg.ID,
	)
	return err
}

const updateStructureInstanceSHash = `-- name: UpdateStructureInstanceSHash :exec
update structure_instance
set shash = ?
where id = ?
`

type UpdateStructureInstanceSHashParams struct {
	Shash []byte
	ID    int64
}

func (q *Queries) UpdateStructureInstanceSHash(ctx context.Context, arg UpdateStructureInstanceSHashParams) error {
	_, err := q.db.ExecContext(ctx, updateStructureInstanceSHash, arg.Shash, arg.ID)
	return err
}
