// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Path struct {
	Hash      []byte
	Structure []byte
	Parent    []byte
}

type Structure struct {
	Hash        []byte
	FirstChild  []byte
	NextSibling []byte
}
