// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getStructure = `-- name: GetStructure :one
select hash, first_child, next_sibling from structure
where hash = ?
limit 1
`

func (q *Queries) GetStructure(ctx context.Context, hash []byte) (Structure, error) {
	row := q.db.QueryRowContext(ctx, getStructure, hash)
	var i Structure
	err := row.Scan(&i.Hash, &i.FirstChild, &i.NextSibling)
	return i, err
}

const listPathsByHash = `-- name: ListPathsByHash :many
select hash, structure, parent from path
where hash = ?
`

func (q *Queries) ListPathsByHash(ctx context.Context, hash []byte) ([]Path, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Path
	for rows.Next() {
		var i Path
		if err := rows.Scan(&i.Hash, &i.Structure, &i.Parent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPath = `-- name: UpsertPath :exec
insert into path (hash, structure, parent)
values (?, ?, ?) on conflict do update set
	parent = excluded.parent
`

type UpsertPathParams struct {
	Hash      []byte
	Structure []byte
	Parent    []byte
}

func (q *Queries) UpsertPath(ctx context.Context, arg UpsertPathParams) error {
	_, err := q.db.ExecContext(ctx, upsertPath, arg.Hash, arg.Structure, arg.Parent)
	return err
}

const upsertStructure = `-- name: UpsertStructure :exec
insert into structure (hash, first_child, next_sibling)
values (?, ?, ?) on conflict do update set
	first_child = excluded.first_child,
	next_sibling = excluded.next_sibling
`

type UpsertStructureParams struct {
	Hash        []byte
	FirstChild  []byte
	NextSibling []byte
}

func (q *Queries) UpsertStructure(ctx context.Context, arg UpsertStructureParams) error {
	_, err := q.db.ExecContext(ctx, upsertStructure, arg.Hash, arg.FirstChild, arg.NextSibling)
	return err
}
